language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  local_dir: src/.vuepress/dist
  target_branch: gh-pages
  verbose: true
  on:
    branch: master