language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: src/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master