language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  local_dir: src/.vuepress/dist
  target-branch: gh-pages
  verbose: true
  on:
    branch: master